close_popup = "qa-GENERIC_LIGHTBOX_CLOSE"
welcome_note = "//h1[contains(text(),'Welcome to Evernote!')]"
close_setup = "PersonalizationFtiModalClose"
close_btn = "//button[@aria-label='Close']"
work = "//h3[text()='Work']"
next_btn = "//button[text()='Next']"
meeting_template = "//h3[text()='Meeting notes']"
logged_in_user = "qa-//span[contains(@class,'EluPykwep6b0dg')]"
logged_in_user_text = "//*[@class='mjp8WyYQODySClV2byHt']"
sign_out = "qa-ACCOUNT_DROPDOWN_LOGOUT"
get_started = "qa-GET_STARTED"
web_browser = "Web Browser"
sign_out = "//span[contains(text(), 'Sign out')]"