note = "qa-CREATE_NOTE"
task = "qa-NAV_TASKS"
new_task_btn = "qa-TASK_DUCHY_CREATE_TASK"
task_name_id = "qa-TASKS_MODAL_TITLE"
create_task_btn = "qa-TASKS_MODAL_SUBMIT"

created_task = "//div[contains(@id, 'qa-TASKS_ITEM_TITLE')]/div[text()='%s']"
things_to_do = "qa-TASKS_MODAL_NOTE_MENU"
go_to_note = "qa-TASKS_MODAL_GOTO_NOTE"
insert = "qa-INSERT_LABEL"
image = "photo"
notes_tab = "//span[text()='Notes']" #qa-NAV_ALL_NOTES"
task_in_notes = "//div[@class='nkDa1']"
para = "//div[@class='para']"
table = "table"
hover_add_row = "//div[@class='SZtnQ']"
