note = "qa-CREATE_NOTE"
task = "qa-NAV_TASKS"
new_task_btn = "qa-TASK_DUCHY_CREATE_TASK"
task_name_id = "qa-TASKS_MODAL_TITLE"
create_task_btn = "qa-TASKS_MODAL_SUBMIT"

created_task = "//div[text()='assignment']"
things_to_do = "qa-TASKS_MODAL_NOTE_MENU"
go_to_note = "qa-TASKS_MODAL_GOTO_NOTE"
insert = "qa-INSERT_LABEL"
image = "photo"
notes_tab = "//span[text()='Notes']"
task_in_notes = "//div[@class='nkDa1']"
en_note = "//en-note[@id='en-note']/div[2]"

para = "//div[@class='para']"
table = "table"
hover_add_row = "//div[@data-testid='enTable-rowInsertion-2']/div[@class='SZtnQ']"
"//div[@data-testid='task-input']/div[text()='yuiop']"
trash_btn = "//button[@data-testid='task-trash']"
data_task = "//div[@data-task='true']"
editor_frame = "qa-COMMON_EDITOR_IFRAME"
select_table = "en-table"
side_table_select = "//div[@class ='handle QZiGN']"